source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# JSON形式のデータを整える
gem "active_model_serializers"

gem "bootsnap", require: false

# 環境毎の設定管理を行う
gem "config"

# ユーザー認証
gem "devise"
gem "devise-i18n"
gem "devise_token_auth"

# enum日本語化
gem "enum_help"

# ページネーション
gem "kaminari"

# 画像のアップロード
gem "carrierwave"

gem "fog-aws"

# 画像のリサイズ
gem "mini_magick"

# AWS SES(認証メール送信)用
gem 'aws-sdk-rails'

# MySQLに接続する
gem "mysql2", "~> 0.5"

gem "puma", "~> 5.0"

# cors設定
gem "rack-cors"

# 日本語化
gem "rails-i18n"

# 環境変数
gem "dotenv-rails", groups: [:development, :test]

gem "rails", "~> 7.0.4"

# タイムゾーン情報を提供する
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
group :development, :test do
  gem "bullet"
  gem "factory_bot_rails"
  gem "faker"
  gem "letter_opener_web"
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
  gem "rspec-rails"
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end
